### ISSUE TITLE
Uncaught inflate exception

### ISSUE THREAD

**Issue by bit-pirate** [stonier/cost_map#7]
When `Inflate` cannot find the provided layer name a STD exception is thrown:

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  CostMap::get(...) : No map layer of type '' available.
```

Looking at the demo inflation code, I would expect I only have to catch ECL exception. Should I implement a catch all or should this exception be caught by Inflate.

PS: The same issue also exists in `Deflate`.

**Comment by stonier** [comment]
It's always good practice to catch the exact exceptions. Especially in a library - if for some reason in the future you're catching unknown exceptions and handling them in the wrong way, then you've hidden (masked) from your user any change to discover that something is going wrong. The symptoms will be much more difficult to track than if you'd let this previously unknown exception to float to the top. This is even more critical when you consider some exceptions can arise through no fault of your library, but because something like memory has run out underneath you - and you need that to get to your user.

**Comment by stonier** [comment]
The doxygen you write should always endeavour to list what exceptions it raises along with the arguments for each function. I _am_ always extremely happy to find libraries that do that rather than having to discover by trial and error. e.g.

```
  /**
   * @brief Inflate...
   *
   * @param layer_source
   * @param layer_destination
   * @param inflation_radius
   * @param inscribed_radius
   * @param cost_map
   * @throw std::out_of_range if no map layer with name `layer` is present.
   */
```

**Comment by bit-pirate** [comment]
:+1: 

I'll add it to the docs along the fix for a related problem here: https://github.com/stonier/cost_map/pull/9

**Comment by bit-pirate** [comment]
Just realised you have already added it.
